### ISSUE TITLE
[v5] Modal isn't returning focus to disclosure

### ISSUE THREAD

**Issue by diegohaz** [fannypackui/fannypack#124]
1. Visit https://v5.fannypack.style/utilities/modal/
2. Click on any "Open modal" button
3. Close the modal by any means

Focus should return to the disclosure button, but it's not happening. The same happens with `Dialog`.

Tried to look into the code to find something, but couldn't figure it out. Other components such as `DropdownMenu` and `Popover` seem to work fine.

**Comment by jxom** [comment]
Oh strange! This used to work... 😅 Might have missed something when migrating between Reakit versions! I'll have a look.

**Comment by jxom** [comment]
Fixed on 1216361685a0025efcab98500e866070f1572af0
