### ISSUE TITLE
Add contribution guidelines

### ISSUE THREAD

**Issue by samantha-wong** [fannypackui/fannypack#33]
Let's put in some guidelines to help guide some poor souls (e.g. me) out of the dark.

**FYI things:**
1. using styled-tools

**Things we easily forget...**
1. adding your config to types
2. editing themes.mdx to include your component config

**Comment by jxom** [comment]
It would be also nice to add guidelines around:

- TypeScript stuff (when it comes out)
- Theming (theming styled.js, when to use stuff from the theme in your components, when to extract stuff out into the theme)
- Accessibility (browser plugins to test a11y, wai-aria attributes, wai-aria reference docs) 
- Adding component as an export in `index.js`
- Template of a component `mdx` file
