### ISSUE TITLE
Font awesome icons don't work when ThemeProvider isStandalone is set

### ISSUE THREAD

**Issue by LightningK0ala** [fannypackui/fannypack#39]
Adding fontawesome icon sets when using fannypack with isStandalone prop in ThemeProvider breaks the app.

**Comment by jxom** [comment]
Hey @LightningK0ala,

The `iconSets` attribute isn't supported in the standalone themes at the moment, however for now, you can add icons to a standalone theme like so:

```jsx
import parseIcons from 'fannypack/parseIcons';
import * as faInfoCircle from '@fortawesome/free-solid-svg-icons/faInfoCircle';
import * as faTimes from '@fortawesome/free-solid-svg-icons/faTimes';

const theme = {
  ...
  Icon: {
    icons: parseIcons([faInfoCircle, faTimes], { prefix: 'solid-', type: 'font-awesome-standalone' })
  }
  ...
}
```

Let me know how it goes.

**Comment by LightningK0ala** [comment]
Looks good! Thanks @jxom.
