### ISSUE TITLE
<Set isVertical> should remove flex-start and flex-wrap.

### ISSUE THREAD

**Issue by hastebrot** [fannypackui/fannypack#44]
Makes no sense to wrap Set's children when `isVertical` is set. 

Also makes sense to fill the width by removing `align-items: flex-start`. But it might not the case if you, e.g. don't want to fill the width of `Button`s.

What it is:

~~~jsx
<Set isVertical>
  <Input />
  <Input placeholder="Jake Moxey" marginTop="major-1" />
</Set>
~~~

What it should be:

~~~jsx
<Set isVertical style={{ alignItems: "unset" }}>
  <Input />
  <Input placeholder="Jake Moxey" marginTop="major-1" />
</Set>
~~~

**Comment by jxom** [comment]
You're right, it doesn't make sense to have flex-wrap set for `isVertical`.

For the case of the `align-items` issue, I think I might add a prop to `<Set>` to have the ability to fill it's children. I think it makes sense to preserve the width of it's children by default.

**Comment by jxom** [comment]
@hastebrot - `<Set>` has a `isFilled` prop now to suit your case. https://fannypack.style/utils/Set#vertical
