### ISSUE TITLE
Access to props?

### ISSUE THREAD

**Issue by joshball** [fannypackui/fannypack#57]
Hi,
Quick question I can't figure out. Is there a way to get access to the props of the components?

For instance, 
```
import { Switch, SwitchProps }from 'fannypack';
```
`reakit `allows you to do so. 
```
import { LabelProps as ReakitLabelProps } from 'reakit/ts';
```

Thanks for the excellent work!

**Comment by jxom** [comment]
Have you tried:

```jsx
import { SwitchProps } from 'fannypack/ts/Switch/Switch';
```

However, it would be nice to import the types straight from the index... Will look into refactoring the exports!

**Comment by joshball** [comment]
I apologize. I didn't catch the extra folders. You have it all right there.
```
export { 
     ButtonProps,
     buttonPropTypes, 
     buttonDefaultProps, 
     LocalButtonProps 
} from 'fannypack/ts/Button/Button';
```
Thank you.

**Comment by joshball** [comment]
BTW, just a note, it appears you can only ask for:

`export { ButtonProps, LocalButtonProps } from 'fannypack/ts/Button/Button'`

If you do either of these:
`export { buttonPropTypes, buttonDefaultProps } from 'fannypack/ts/Button/Button'`

it results in 

`Uncaught Error: Cannot find module 'fannypack/ts/Button/Button'`

Not sure why, both are exported in the code. Maybe there is a stripping process?

**Comment by jxom** [comment]
Ahh, think you'll need to omit the `/ts/` from the path for the prop types/default props as they're not TS related

**Comment by jxom** [comment]
Ahh, think you'll need to omit the `/ts/` from the path for the prop types/default props as they're not TS related
