### ISSUE TITLE
Override Border on Input

### ISSUE THREAD

**Issue by HeavyByte** [fannypackui/fannypack#68]
I cannot find a way to remove or override the border style using the Input component. Since under the covers it looks like <Input /> is an <input/> wrapped in a <div> anytime I style 
 the border for <Input/> it just styles the <div> that <input> is wrapped in.

I have tried overriding styles using CSS props, styled-components, and emotion (css, styled) but they all just style the div that input in wrapped in.

**Comment by jxom** [comment]
Hi, have you tried overriding the styling with the [`<Input> theme config`](https://fannypack.style/form/input#theming)?

See how to [override the default theme here](https://fannypack.style/styling/theming)

**Comment by HeavyByte** [comment]
I was able to get this to work a little bit but I am not sure this solves the issue. If I want more than one style of Input in my app, one with borders and one without, this doesn't seem to work. I initially thought I'll just create a class on the theme but again I have no way to pass that class name to the native input.

Example:
```
const theme = {
    Input: {
        base: css`
            .noBorder {
                border: none;
                box-shadow: none;
            }
        `
    }
}
```

```
<Input className="noBorder">
```

**Comment by jxom** [comment]
Ok, what if you try adding a prop to the input like:

```javascript
<Input noBorder>
```

then in your theme:

```javascript 
const theme = {
  Input: {
    base: css`
      ${props => props.noBorder && css`
        border: none;
        box-shadow: none;
      `}
    `
  }
}
```

**Comment by HeavyByte** [comment]
Thank you for your help! I found a simple way to do this with the styled-component or emotion by using the css selector.

```
import { Input, styled } from "fannypack"

<StyledInputNoBorder />

const StyledInputNoBorder = styled(Input)`
    input {
        border: none;
        padding: 0;
        margin: 0;
    }
`
```
This will give the styles to the child input element.
