### ISSUE TITLE
TypeError: cannot read property 'viewBoxWidth' of undefined related to Icons

### ISSUE THREAD

**Issue by Cigoler** [fannypackui/fannypack#69]
I keep getting the following error when trying to use anything with an Icon property:
    
    TypeError: Cannot read property 'viewBoxWidth' of undefined

I've installed both solid and regular fontawesome libraries as described in the documentation. I'm new to react so I could be doing something really dumb but I've tried just copy and pasting the code in the docs into the playroom provided by yourselves and it throws up the same error.

Any help is greatly appreciated.

**Comment by jxom** [comment]
Hi, can you please send me your usage of Icon & also your theme config? Thanks!

**Comment by jxom** [comment]
Oh, sorry, you experienced that in playroom. That’s probably happening as icons aren’t imported into playroom :(

**Comment by Cigoler** [comment]
Hi Jxom, apologies in advance if I'm just being thick, but this is what I've got. I'm using Gatsbyjs and trying to implement 'fannypack' (which has a slightly different meaning in english but hey ho 👯 ).

```
import { ThemeProvider } from 'fannypack';
import { faPen, faShare, faFileSignature, faIgloo, faSearch, faClipboard, faThumbsUp } from '@fortawesome/free-solid-svg-icons';
import { faAddressBook } from '@fortawesome/free-regular-svg-icons';
const theme = {
  Icon: {
    iconSets: [
      {
        icons: [faPen, faShare, faFileSignature, faIgloo, faSearch, faClipboard, faThumbsUp],
        prefix: 'solid-',
        type: 'font-awesome'
      },
      {
        icons: [faAddressBook],
        prefix: 'regular-',
        type: 'font-awesome'
      }
    ]
  }
};

const IndexPage = () => (
  <ThemeProvider theme={theme}>
    <Tabs.Container>
      {tabs => (
        <Tabs>
          <Tabs.Tab tab="documents" {...tabs}>
            <Icon icon="solid-file" marginRight="major-1" /> Documents
          </Tabs.Tab>
          <Tabs.Tab tab="messages" {...tabs}>
            <Icon icon="solid-comments" marginRight="major-1" /> Messages
          </Tabs.Tab>
          <Tabs.Tab tab="profile" {...tabs}>
            <Icon icon="solid-user" marginRight="major-1" /> Profile
          </Tabs.Tab>
        </Tabs>
      )}
    </Tabs.Container>
  </ThemeProvider>
);
```

**Comment by claudianadalin** [comment]
Hi, it seems like you aren't importing the specific icons you are trying to use. Try importing `faUser`, `faFile` and `faComments` as well from `@fortawesome/free-solid-svg-icons`, and adding it to the icon set. 

e.g.

```
import {faPen, faShare, faFileSignature, faIgloo, faSearch, faClipboard, faThumbsUp, faUser, faFile, faComments} from '@fortawesome/free-solid-svg-icons';
```

and then to add to the icon set:

```
const theme = {
  Icon: {
    iconSets: [
      {
        icons: [faPen, faShare, faFileSignature, faIgloo, faSearch, faClipboard, faThumbsUp, faUser, faFile, faComments],
        prefix: 'solid-',
        type: 'font-awesome'
      },
      {
        icons: [faAddressBook],
        prefix: 'regular-',
        type: 'font-awesome'
      }
    ]
  }
};
```

**Comment by jxom** [comment]
Hey @Cigoler, @thepenskefile's solution should work. 

Also, "Fannypack" used to be called "Bumbag", however, we renamed to Fannypack as it was a more well-known term used globally, and assumed people who are used to "Bumbag" would know that a "Fannypack" is the same thing. In Australia, we call it a "Bumbag".

**Comment by Cigoler** [comment]
That did the trick guys, thanks. Sorry for bothering you with a silly error on my part, I jumped to conclusions with it not working in the playground.

@jxom Although I am aware of the relation between the two, being British and hearing 'fanny' is still amusing to me. Please forgive my childish sense of humour 💃
