### ISSUE TITLE
Webpack build fails due to error in ToastContainer

### ISSUE THREAD

**Issue by Pegase745** [fannypackui/fannypack#70]
Hello,

Does this ring a bell to anyone please ? 

```console
WARNING in ./node_modules/fannypack/es/Toast/ToastContainer.js 84:23-32
"export 'Container' was not found in 'reakit'
  @ ./node_modules/fannypack/es/ThemeProvider/index.js
  @ ./node_modules/fannypack/es/index.js
  @ ./src/index.tsx
```
https://github.com/fannypackui/fannypack/blob/master/src/Toast/ToastContainer.tsx#L3

(great project, by the way!)

**Comment by Pegase745** [comment]
@jxom any ideas please ? I would've loved to use the lib..

**Comment by jxom** [comment]
Hmm. Do you have a custom Babel & Webpack config you are using?
