### ISSUE TITLE
Setting text color when overriding palette for Button

### ISSUE THREAD

**Issue by axhamre** [fannypackui/fannypack#77]
I'm using a `Button` like this:

```
<Button palette="primary">test</Button>
```
I'm overrriding the `primary` palette color successfully with this code:

```
theme = {
  palette: {
    primary: '#4182c3'
  }
};
```

The text color gets converted though to `#000000` at the same time, from being `#ffffff` before my override.

What's the mechanism changing the text color here? 

Is the text color for a specific palette color possible to define?

**Comment by jxom** [comment]
Hey! 

Yes, that behaviour is expected as fannypack chooses the best color to match with the background color to meet AA accessibility requirements. 

If you want to ignore this and override it though, you can set ‘primaryInverted’ to the color you wish.

**Comment by axhamre** [comment]
Thanks, that's brilliant! 👌

Just a quick note though. I'm admittedly not knowledgeable in the field, but spontaneously I'd say that the second renders a higher degree of contrast than the first button.

<img width="115" alt="Screenshot 2019-04-27 09 58 58" src="https://user-images.githubusercontent.com/1907343/56846807-ddcb7f00-68d3-11e9-83b0-03480da3bd28.png">
<img width="115" alt="Screenshot 2019-04-27 09 58 44" src="https://user-images.githubusercontent.com/1907343/56846808-ddcb7f00-68d3-11e9-9c95-9795b633732e.png">

**Comment by jxom** [comment]
Hmm, weird, it may look like that, but chrome devtools disagrees!

<img width="199" alt="Screen Shot 2019-04-27 at 7 17 25 pm" src="https://user-images.githubusercontent.com/7336481/56847661-3117ee80-6921-11e9-861d-24d460ff178d.png">

<img width="202" alt="Screen Shot 2019-04-27 at 7 17 35 pm" src="https://user-images.githubusercontent.com/7336481/56847662-32e1b200-6921-11e9-8e41-592a2feb2c69.png">
